//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRI.Messaging.Patterns.Analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRI.Messaging.Patterns.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls to RequestAsync should be awaited.
        /// </summary>
        internal static string Mp0100Description {
            get {
                return ResourceManager.GetString("Mp0100Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to RequestAsync not awaited..
        /// </summary>
        internal static string Mp0100MessageFormat {
            get {
                return ResourceManager.GetString("Mp0100MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to RequestAsync not awaited..
        /// </summary>
        internal static string Mp0100Title {
            get {
                return ResourceManager.GetString("Mp0100Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls to RequestAsync with error events should be guarded with try/catch.
        /// </summary>
        internal static string Mp0101Description {
            get {
                return ResourceManager.GetString("Mp0101Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to RequestAsync with error event but no try/catch..
        /// </summary>
        internal static string Mp0101MessageFormat {
            get {
                return ResourceManager.GetString("Mp0101MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to RequestAsync with error event but no try.catch..
        /// </summary>
        internal static string Mp0101Title {
            get {
                return ResourceManager.GetString("Mp0101Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string Mp0102Description {
            get {
                return ResourceManager.GetString("Mp0102Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to RequestAsync can be replaced with IConsumer&lt;T&gt; implementations..
        /// </summary>
        internal static string Mp0102MessageFormat {
            get {
                return ResourceManager.GetString("Mp0102MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider a looser-coupled, message handler class..
        /// </summary>
        internal static string Mp0102Title {
            get {
                return ResourceManager.GetString("Mp0102Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestAsync models message-event interaction, not event-event interaction.
        /// </summary>
        internal static string Mp0103Description {
            get {
                return ResourceManager.GetString("Mp0103Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending event with RequestAsync..
        /// </summary>
        internal static string Mp0103MessageFormat {
            get {
                return ResourceManager.GetString("Mp0103MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestAsync called with event as message to send..
        /// </summary>
        internal static string Mp0103Title {
            get {
                return ResourceManager.GetString("Mp0103Title", resourceCulture);
            }
        }
    }
}
